---
apiVersion: xl-release/v1
kind: Templates
spec:
  - directory: Test
    children:
      - template: GithubWebhooksTemplate
        scheduledStartDate: 2020-07-23T09:00:00-04:00
        phases:
          - phase: New Phase
            tasks:
              - name: Print HelloWorld
                type: xlrelease.ScriptTask
                script: |-
                  variables = releaseApi.getVariables(release.id)
                  for var in variables:
                     print(var.key +' '+ var.value)
            color: '#0079BC'
        variables:
          - type: xlrelease.StringVariable
            key: repository_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: branch_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_status
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_author
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_action
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_assignees
            requiresValue: false
          - type: xlrelease.ListStringVariable
            key: pull_request_labels
            requiresValue: false
          - type: xlrelease.MapStringStringVariable
            key: pull_request_map
            requiresValue: false
        scriptUsername: admin
        scriptUserPassword: !value "xlrelease_Release_GithubWebhooksTemplate_scriptUserPassword"
        riskProfile: Default risk profile
      - name: Github Push Event Trigger
        type: events.EventBasedTrigger
        description: Sample for github push event
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: ${event.head_commit.message}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.name}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.repository.default_branch}
          - type: xlrelease.ListStringValue
            targetProperty: tags
            value:
              - ${event.head_commit.timestamp}
          - type: xlrelease.StringValue
            targetProperty: template
            value: GithubWebhooksTemplate
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: Github Webhooks Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.ExpressionEventFilter
          expressions:
            - type: events.EventFilterExpressionItem
              path: event.ref
              operator: INCLUDES
              valueType: STRING
              value: master
            - type: events.EventFilterExpressionItem
              path: event.repository.name
              operator: EQUALS
              valueType: STRING
              value: xlr-github-webhooks-samples
      - name: Github Pull Request Event Trigger
        type: events.EventBasedTrigger
        description: Sample trigger for pull requests.
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: PR created id (${event.pull_request.id}) by ${event.sender.login} assigned
              to ${event.requested_reviewer.login}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.name}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_action]
            value: ${event.action}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.pull_request.head.ref}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_status]
            value: ${event.pull_request.state}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_author]
            value: ${event.sender.login}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_assignees]
            value: ${event.requested_reviewer.login}
          - type: xlrelease.ListStringValue
            targetProperty: tags
            value:
              - ${event.pull_request.created_at}
          - type: xlrelease.VariableValue
            targetProperty: variables[pull_request_map]
            variableKey: event.pull_request
          - type: xlrelease.VariableValue
            targetProperty: variables[pull_request_labels]
            variableKey: event.pull_request.labels
          - type: xlrelease.StringValue
            targetProperty: template
            value: GithubWebhooksTemplate
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: Github Webhooks Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.GroovyEventFilter
          expr: "event.action in [\"opened\",\"reopened\",\"syncronized\"] &&\nevent.pull_request.labels.name.contains(\"\
        build\") && \nevent.pull_request.base.ref == \"master\" &&\nevent.repository.name\
        \ == \"xlr-github-webhooks-samples\""
